import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "@/styles/globals.scss";

const onestSans = Onest({
  variable: "--font-Onest-sans",
  subsets: ["latin"],
  weight: ["400", '500', "700"]
});

export const metadata: Metadata = {
  title: "Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onestSans.className}`}>
        {children}
      </body>
    </html>
  );
}
